Force using C11 for Guile builds on Travis CI
Compiling code including Guile headers with default compiler options
doesn't work any more since a recent (~2020-05-05) update to Guile 3.0.2
on Homebrew (2.2.7 was used previously) due to

error: redefinition of typedef 'scm_print_state' is a C11 feature

in libguile/print.h and scm.h headers.

Work around this by enabling C11 for this build by explicitly setting
CSTD. Note that we can't just use CPP11=1 for this build, because this
would also enable C++11-specific tests that are not currently supported
by Guile module.