Fix naming conflict between class and method
```
variable_replacement.f90:33:30:

  type, extends(A), public :: B
                              1
Error: Component 'a' of 'b' at (1) has the same name as an inherited type-bound procedure
```