Fix cpp_template_pack testcase workarounds for D
Workaround to avoid:
  Warning 314: 'Object' is a D keyword, renaming to '_Object'

Also when instantiating two Object<> templates works around another
problem:
  Error: 'new__Object' is multiply defined in the generated target language module.

Adjustments to D's %keywordwarn would probably avoid this though.