Correct instantiate of std::basic_istream and std::basic_ostream
Instantiate them correctly before they are used as member variables to
fix regression in e07957ad4c2e501e349d1c7eb8032f4c8a387f1f.

std::cin is read-only! ...

checking python testcase li_std_string_extra (with run test)
In file included from /usr/include/c++/9/ios:44,
                 from /usr/include/c++/9/ostream:38,
                 from /usr/include/c++/9/iostream:39,
                 from li_std_stream_wrap.cxx:3278:
/usr/include/c++/9/bits/basic_ios.h: In member function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’:
/usr/include/c++/9/bits/basic_ios.h:67:11: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private within this context
   67 |     class basic_ios : public ios_base
      |           ^~~~~~~~~
In file included from /usr/include/c++/9/ios:42,
                 from /usr/include/c++/9/ostream:38,
                 from /usr/include/c++/9/iostream:39,
                 from li_std_stream_wrap.cxx:3278:
/usr/include/c++/9/bits/ios_base.h:870:5: note: declared private here
  870 |     operator=(const ios_base&);
      |     ^~~~~~~~
In file included from /usr/include/c++/9/iostream:40,
                 from li_std_stream_wrap.cxx:3278:
/usr/include/c++/9/istream: In member function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’:
/usr/include/c++/9/istream:58:11: note: synthesized method ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ first required here
   58 |     class basic_istream : virtual public basic_ios<_CharT, _Traits>
      |           ^~~~~~~~~~~~~
li_std_stream_wrap.cxx: In function ‘int Swig_var_cin_set(PyObject*)’:
li_std_stream_wrap.cxx:13992:19: note: synthesized method ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ first required here
13992 |       std::cin = *temp;