Revert "Delete assignment operator if marked as ignored"
This reverts commit 6bb057508d0126ac3f1e785d339b0c101f6b58d8. It causes the Java boost shared pointer tests to fail:

```
../../../../../src/swig/Examples/test-suite/java/li_boost_shared_ptr_runme.java:451: error: cannot find symbol
      m.setMemberValue(k);
       ^
  symbol:   method setMemberValue(Klass)
  location: variable m of type MemberVariables
../../../../../src/swig/Examples/test-suite/java/li_boost_shared_ptr_runme.java:520: error: cannot find symbol
      try { m.setMemberValue(null); throw new RuntimeException("Failed to catch null pointer"); } catch (NullPointerException e) {}
             ^
  symbol:   method setMemberValue(<null>)
  location: variable m of type MemberVariables
../../../../../src/swig/Examples/test-suite/java/li_boost_shared_ptr_runme.java:547: error: cannot find symbol
      li_boost_shared_ptr.setGlobalValue(k);
                         ^
  symbol:   method setGlobalValue(Klass)
  location: class li_boost_shared_ptr
../../../../../src/swig/Examples/test-suite/java/li_boost_shared_ptr_runme.java:557: error: cannot find symbol
      try { li_boost_shared_ptr.setGlobalValue(null); throw new RuntimeException("Failed to catch null pointer"); } catch (NullPointerException e) {}
                               ^
  symbol:   method setGlobalValue(<null>)
  location: class li_boost_shared_ptr
4 errors
make: *** [li_boost_shared_ptr.cpptest] Error 1
```