Revert previous commit as it breaks setting arbitrary attributes on builtin wrapped types
When using -builtin and -DSWIG_HEAPTYPES.

Otherwise there are two testcase failures when trying to set arbitrary
attributes onto the wrapped Python types:

Traceback (most recent call last):
  File "/home/william/swig/github/swig/Examples/test-suite/python/./li_std_vector_back_reference_runme.py", line 8, in <module>
    size = first_element().size
           ^^^^^^^^^^^^^^^
  File "/home/william/swig/github/swig/Examples/test-suite/python/./li_std_vector_back_reference_runme.py", line 6, in first_element
    return v[0]
           ~^^^
AttributeError: 'li_std_vector_back_reference.Wheel' object has no attribute '__swig_container'
make[1]: *** [Makefile:143: li_std_vector_back_reference.cpptest] Error 1

Traceback (most recent call last):
  File "/home/william/swig/github/swig/Examples/test-suite/python/./struct_value_runme.py", line 15, in <module>
    b.added = 123
    ^^^^^^^
AttributeError: 'struct_value.Bar' object has no attribute 'added'
make[1]: *** [Makefile:141: struct_value.cpptest] Error 1