Check if `__cplusplus` is defined before comparing it
With SWIG 4.2.0 (and master as of today), I get:

    bt2/native_bt.c:138:5: error: "__cplusplus" is not defined, evaluates to 0 [-Werror=undef]
      138 | #if __cplusplus >=201103L
          |     ^~~~~~~~~~~

The lines in question are:

  138 #if __cplusplus >=201103L
  139 # define SWIG_NULLPTR nullptr
  140 #else
  141 # define SWIG_NULLPTR NULL
  142 #endif

Change the pre-processor checks to see if `__cplusplus` is defined
before comparing it.