Travis Go testing moved to xenial
The default Go 1.11 version on Travis doesn't work with C++11/C++14:

  gcc_libinit.c:110:3: error: implicit declaration of function ‘nanosleep’

so switch to another gimme version of Go.